# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitHub_searcher_task' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitHub_searcher_task
	pod 'Alamofire'
  	pod 'Kingfisher'
end
